// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://drfufywfplvjrpmqfqlz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRyZnVmeXdmcGx2anJwbXFmcWx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0OTUzNzEsImV4cCI6MjA2MzA3MTM3MX0.A7gtD1rP2Aj2EpLn7hxRaFa-JZaKCVLkEIjAszTKrJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);